- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import VPC variables
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2-vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostsnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    
    - debug:
        var: vpcout

    - name: create public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          name: vprofile-pubsub1
      register: pubsub1_out
    
    - name: create public subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          name: vprofile-pubsub2
      register: pubsub2_out

    - name: create private subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{present}}"
        cidr: "{{PrivSub1Cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub3
        register: privsub3_out

    - name: create private subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{present}}"
        cidr: "{{PrivSub2Cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub3
        register: privsub3_out

   - name: create private subnet3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{present}}"
        cidr: "{{PrivSub3Cidr}}"
        map_public: yes
        resource_tags: 
          name: vprofile-privsub3
        register: privsub3_out




  